### ISSUE TITLE
Sample of multiple colors, outside of a view?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [jinatonic/confetti#1]
As if you've bought something...
Maybe colors like on this:
https://cdn-images-1.medium.com/max/800/1*cipIsoMzYhdxGU_p8CdRzA.png

**Comment by jinatonic** [comment]
Hello,

I am unsure what your question is. You can use arbitrary bitmaps for your confetti if you wish.

Please re-open the issue if you wish to elaborate on the problem that you are facing. Thank you!

**Comment by AndroidDeveloperLB** [comment]
The sample includes brown rectangles. I just think that confetti is more colorful than that. I suggest making them more colorful, like what I show on the image you have on the main page here.

**Comment by jinatonic** [comment]
Ah I see what you mean. You can configure the confetti however you want. Showing them in multiple colors is actually extremely simple if you use the provided utils class to generate square/triangle/rectangle confetti. I just chose the various shades of gold color because that's what we use in the Robinhood app.

**Comment by AndroidDeveloperLB** [comment]
Is it a stocks app ? In which case do you use it? When the user gets a huge increase of his money?

Also, BTW, I've noticed a bug on the sample: when I click on "infinite" button a lot, I notice that the starting point of the confetti creations goes down (in Y coordinate) more and more. 
However, in order to notice it, you really have to get a lot of confetti...

**Comment by jinatonic** [comment]
Yes, Robinhood is a stock trading app. You can check us out here: https://play.google.com/store/apps/details?id=com.robinhood.android&hl=en

Unfortunately the feature is not rolled out yet so I cannot say anything on the topic :) 

When you click infinite a lot, each infinite stream of confetti adds onto the other. The starting point is always on the top, but there might be some weird illusions due to the large number of confetti that may make it seem that the confetti are starting at a lower point.
