### ISSUE TITLE
ConfettiManager leaking

### ISSUE THREAD

**Issue by krokyze** [jinatonic/confetti#16]
Hi,

I'm using LeakCanary and getting these leaks really often.
![LeakCanay stacktrace](https://puu.sh/tB65S/5449b2e90b.png)

I'm not 100% sure, but I think that in ConfettiManager terminate method you should call animator.removeAllUpdateListeners.

**Comment by jinatonic** [comment]
There shouldn't be a leak regarding the update listeners because the animator is contained entirely within the `ConfettiManager` class, and inside `terminate` we cancel the running animator if there is one.

Are you keeping a reference of `ConfettiManager` somewhere outside of your context? `ConfettiManager` has a handle on the underlying view which has a handle on the underlying context so that can potentially cause a leak.

**Comment by krokyze** [comment]
I wasn't keeping any references of ConfettiManager, but it looks that the leak was because I didn't unbind ConfettiView in Fragment onDestroyView.
