### ISSUE TITLE
Can't be displayed above dialog

### ISSUE THREAD

**Issue by eugeneroz** [jinatonic/confetti#40]
Steps:
1. Show Fragment Dialog
2. Animate Confetti

Actual:
Confetti displayed below dialog since it's attached to decor view

Expected:
It should be customisable if effect should be above or below dialog

**Comment by jinatonic** [comment]
can you not attach the confetti to the underlying activity's decorview if you want it below the dialog?

**Comment by eugeneroz** [comment]
1. I want that confetti will be always on top.
2. It should be also on top of fragment dialog. Currently, you see animation only when it's out of dialog border.

I have worked around it by activity with dialog theme. But, it's ugly solution

**Comment by jinatonic** [comment]
ah i see, i misunderstood your original question. its because the activity shows the dialog on top of its base view so that confetti shows up below. hm I'm not sure if there is an easy way around this unfortunately because you have to provide confetti with a parent in which it can draw on, and trying to figure out an API to specify what views it should be above / below isn't feasible. 

i think the dialog theme would be the right way to do it, or maybe via some overlay view on top of the activity (similar to what activity transitions use), but I don't know exactly how you would do it.
