### ISSUE TITLE
What does fisrtTime and secondTime mean in computeBound()?

### ISSUE THREAD

**Issue by pahoehoe** [jinatonic/confetti#5]
snippet：

```
( if (targetTime == null || targetTime < 0) {
//                 https://www.wolframalpha.com/input/
//                 ?i=solve+for+t+in+(d+%3D+x+%2B+v+*+t+%2B+0.5+*+a+*+t+*+t)

                final double tmp = Math.sqrt(
                        2 * acceleration * bound - 2 * acceleration * initialPos
                                + velocity * velocity);

                final double firstTime = (-tmp - velocity) / acceleration;
                if (firstTime > 0) {
                    return (long) firstTime;
                }

                final double secondTime = (tmp - velocity) / acceleration;
                if (secondTime > 0) {
                    return (long) secondTime;
                }

                return Long.MAX_VALUE;
            })
```

Hi,Confetti will Accelerate until reaching bound because it doest have targetTime.So tmp is the time  of the reaching Bound.Why you have to calculate firstTime and secondTime to determine the reaching bound time?

**Comment by jinatonic** [comment]
Hello,

If you look at the solutions for solving for `time` in the distance formula here:

https://www.wolframalpha.com/input/?i=solve+for+t+in+(d+%3D+x+%2B+v+*+t+%2B+0.5+*+a+*+t+*+t)

You'll see that the answer has two possible solutions since that it's a quadratic formula. Here we are simply solving for both solutions and using whichever one that results in a positive `time` answer.

**Comment by pahoehoe** [comment]
Thanks for your answer,It is really helpful.
